### PR TITLE
Sous Chefs Adoption

### PR DESCRIPTION
**Pull request by ramereth**
# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by bmhughes — APPROVED** [review]
LGTM

**Review by jeffbyrnes — APPROVED** [review]

**Comment by ramereth** [comment]
@jeffbyrnes @bmhughes @Xorima Do we do a major release for Sous Chef adoption?

**Comment by Xorima** [comment]
Minor normally

**Pull request merged**
